author: nimoc
subtitle: 'æŠ€æœ¯åšå®¢'
description: 'å‰ç«¯,åç«¯,å›¢é˜Ÿåä½œ,ç¼–ç å¿ƒå¾—'
keyword: nimoc,nimo
favicon: https://avatars.githubusercontent.com/u/3949015?s=460&v=4

excerpt_link: é˜…è¯»å…¨éƒ¨å†…å®¹

menu:
 ä¸»é¡µ: /
 æ ‡ç­¾: /tags/
 æ—¶é—´çº¿: /archives/
 å¼€æºé¡¹ç›®: /project/
 å…³äºæˆ‘: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# # donate
# donate: true
#
# # qrcode
# qrcode: true

# comment
# you can set gitment, uyan or disqus

# comment: gitment
#
# # gitment config
# gitment_owner: nimoc
# gitment_repo: nimoc.github.io
# gitment_oauth_id: 0f87e490e00ee3fd87ef
# gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id:
google_analytics:
# disqus config
disqus_shortname:

about:
  banner: https://pic4.zhimg.com/80/v2-4df3b54a4f98886029524274a9cbbe35_r.jpg
  avatar: https://avatars.githubusercontent.com/u/3949015?s=460&v=4
  description: "ğŸ‘Œ ä¼˜ç§€çš„è®¾è®¡ï¼Œç®€æ´å®ç°ï¼Œæ»¡è¶³å¤æ‚çš„éœ€æ±‚ã€‚"
  # weibo_username: yanm1ng
  #twitter_username: yanm1ng
  github_username: nimoc
  zhihu_username: nimoc
  #douban_username: yanm1ng
  #linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
